---
- name: Install Python 3 and pip3 using raw (to bypass interpreter issues)
  raw: sudo yum install -y python3 python3-pip

- name: Install Docker SDK for Python
  pip:
    name: docker
    executable: pip3

- name: Downgrade urllib3 to a compatible version (1.26.x)
  pip:
    name: urllib3==1.26.6  # Compatible with OpenSSL 1.0.2
    executable: pip3
    state: present

- name: Install Docker manually using raw (Amazon Linux 2)
  raw: sudo yum install -y docker

- name: Ensure Docker service is started
  systemd:
    name: docker
    state: started
    enabled: true


- name: Copy index.html to remote server
  copy:
    src: ../../index.html  # This is the path on your local machine
    dest: /tmp/index.html  # This is where it will be copied on the remote server

- name: Run Nginx container
  docker_container:
    name: nginx
    image: nginx
    state: started
    ports:
      - "80:80"
    volumes:
    - /tmp/:/usr/share/nginx/html/:ro