---
- name: Install Python 3 and pip3
  yum:
    name:
      - python3
      - python3-pip
    state: present

- name: Install Docker SDK for Python
  pip:
    name: docker
    executable: pip3  # Ensure the SDK is installed using Python 3's pip

- name: Install Docker (Amazon Linux 2)
  yum:
    name: docker
    state: present

- name: Ensure Docker service is started
  systemd:
    name: docker
    state: started
    enabled: true

- name: Run Nginx container
  docker_container:
    name: nginx
    image: nginx
    state: started
    ports:
      - "80:80"
