---
- name: Install Python Docker SDK
  pip:
    name: docker
    state: present
    executable: pip3

- name: Start and enable Docker
  service:
    name: docker
    enabled: true
    state: started

- name: Run Nginx container
  docker_container:
    name: nginx
    image: nginx
    state: started
    ports:
      - "80:80"
